version: '3.8'

services:
  app:
    build: .
    container_name: ${APP_NAME}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: ${APP_NAME}_server
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: docker_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: docker_db
      MAX_EXECUTION_TIME: 3000
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 512M
    networks:
      - laravel


networks:
  laravel:

volumes:
  db_data:
